# Kubernetes < v1.9
# apiVersion: extensions/v1beta1
# Kubernetes >= v1.9
apiVersion: extensions/v1beta2
kind: DaemonSet
metadata:
  name: sematext-agent
spec:
  template:
    metadata:
      labels:
        app: sematext-agent
    spec:
      nodeSelector: {}
      hostNetwork: true
      dnsPolicy: "ClusterFirst"
      restartPolicy: "Always"
      containers:
      - name: sematext-agent
        image: sematext/sematext-agent-docker:latest
        imagePullPolicy: "Always"
        env:
        - name: SPM_TOKEN
          value: "YOUR_SPM_TOKEN"
        - name: LOGSENE_TOKEN
          value: "YOUR_LOGSENE_TOKEN"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
          - mountPath: /etc/localtime
            name: localtime
          - mountPath: /rootfs
            name: rootfs
            readOnly: true
#          - mountPath: /etc/logagent
#            name: patterns
        securityContext:
          privileged: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: rootfs
          hostPath:
            path: /
#        - name: patterns
#          configMap:
#            name: sematext-agent-patterns
#            items:
#            - key: patterns.yml
#              path: patterns.yml
